### ISSUE TITLE
CNF formula example

### ISSUE THREAD

**Issue by jaanos** [bjur/SAT_solver#3]
It appears that you haven't included an example of a CNF formula generated by you, whose satisfiability can be demonstrated by your SAT solver, as requested in the instructions for the homework. Please include one, so I can link to it on the course repository and then use it to run tests.

**Comment by Tilenk** [comment]
Example added, see README.

**Comment by bjur** [comment]
Remaining examples added, also a line of code was commented out in wrapper file (run.py) for a more clear way of dealing with input files.
