### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by jaanos** [bjur/SAT_solver#5]
The output for a satisfiable input should be a just list of integers separated by spaces without any other information.

This will let me simplify my [attempt](https://github.com/jaanos/LVR-2016/blob/master/hw-satsolver/run/run-sml.py) at calling your program - ideally, it should consist of just a single program or function call.

**Comment by bjur** [comment]
Fixed, program should now return the int values for literals evaluated as positive in the solution, sorry for inconvenience

**Comment by bjur** [comment]
Should be fine now, fixed -1 return and added negative terms.
